#!/bin/bash

# Demo script for AI Service hackathon presentation
# This script demonstrates the AI Service endpoints

set -e

echo "🚀 AI Service Demo Script"
echo "========================="
echo ""

# Configuration
API_URL="http://localhost:3004"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_step() {
    echo -e "${BLUE}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

# Check if service is running
print_step "Checking if AI Service is running..."
if curl -s "$API_URL/health" > /dev/null 2>&1; then
    print_success "AI Service is running on $API_URL"
else
    echo "❌ AI Service is not running!"
    echo "Please start it with: cd services/ai-service && pnpm dev"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Demo 1: Explain Vulnerability
print_step "Demo 1: AI Vulnerability Explanation"
print_info "Sending a SQL injection vulnerability for analysis..."
echo ""

EXPLAIN_RESPONSE=$(curl -s -X POST "$API_URL/api/ai/explain" \
  -H "Content-Type: application/json" \
  -d '{
    "vulnerabilityId": "vuln-sql-001",
    "context": {
      "code": "const query = \"SELECT * FROM users WHERE username = '\'\" + username + \"'\' AND password = '\''\" + password + \"'\'\";\ndb.query(query);",
      "language": "javascript",
      "severity": "critical",
      "type": "sql-injection"
    }
  }')

if echo "$EXPLAIN_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
    print_success "Vulnerability explained successfully!"
    echo ""
    echo "Explanation:"
    echo "$EXPLAIN_RESPONSE" | jq -r '.data.explanation' | head -5
    echo "..."
    echo ""
    CONFIDENCE=$(echo "$EXPLAIN_RESPONSE" | jq -r '.data.confidence')
    print_info "AI Confidence: $(echo "scale=0; $CONFIDENCE * 100 / 1" | bc)%"
else
    echo "Response: $EXPLAIN_RESPONSE"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Demo 2: Generate Fix
print_step "Demo 2: AI Code Fix Generation"
print_info "Generating secure code to fix the vulnerability..."
echo ""

FIX_RESPONSE=$(curl -s -X POST "$API_URL/api/ai/fix" \
  -H "Content-Type: application/json" \
  -d '{
    "vulnerabilityId": "vuln-sql-001",
    "includeTests": true
  }')

if echo "$FIX_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
    print_success "Code fix generated successfully!"
    echo ""
    echo "Fixed Code:"
    echo "$FIX_RESPONSE" | jq -r '.data.fixedCode' | head -10
    echo "..."
    echo ""
    print_info "Fix explanation:"
    echo "$FIX_RESPONSE" | jq -r '.data.explanation' | head -3
    echo ""
else
    echo "Response: $FIX_RESPONSE"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Demo 3: Generate PR
print_step "Demo 3: Automated Pull Request Creation"
print_info "Creating a PR with multiple vulnerability fixes..."
echo ""

PR_RESPONSE=$(curl -s -X POST "$API_URL/api/ai/generate-pr" \
  -H "Content-Type: application/json" \
  -d '{
    "vulnerabilityIds": ["vuln-sql-001", "vuln-xss-002"],
    "title": "🔒 Security fixes: SQL Injection and XSS vulnerabilities",
    "description": "Automated security fixes generated by AI Service for critical vulnerabilities found in the codebase."
  }')

if echo "$PR_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
    print_success "Pull Request created successfully!"
    echo ""
    PR_URL=$(echo "$PR_RESPONSE" | jq -r '.data.url')
    PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.data.prNumber')
    FILES_CHANGED=$(echo "$PR_RESPONSE" | jq -r '.data.filesChanged')
    LINES_ADDED=$(echo "$PR_RESPONSE" | jq -r '.data.linesAdded')
    
    print_info "PR #$PR_NUMBER: $PR_URL"
    print_info "Files changed: $FILES_CHANGED"
    print_info "Lines added: $LINES_ADDED"
    echo ""
    echo "PR Description:"
    echo "$PR_RESPONSE" | jq -r '.data.description' | head -10
    echo "..."
else
    echo "Response: $PR_RESPONSE"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

print_success "Demo completed successfully!"
echo ""
echo "Summary:"
echo "✅ Analyzed vulnerability with AI"
echo "✅ Generated secure code fix"
echo "✅ Created automated pull request"
echo ""
print_info "This demonstrates a complete workflow from vulnerability detection to automated remediation!"
